version: "3.3"

services:
  app:
    container_name: evaluar-cursos-app
    image: evaluar-cursos-i
    build:
      context: .
    ports:
      - "8080:80"
    networks:
      - evaluar-cursos
  
networks:
  evaluar-cursos:
    external : true
